name: Deploy app-ads.txt

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Verify files
        run: |
          if [ ! -f public/app-ads.txt ]; then
            echo "❌ Error: public/app-ads.txt not found"
            exit 1
          fi
          echo "✔ All files exist"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
