name: Deploy Static HTML

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Override deprecated upload-artifact v3
      - name: Override deprecated artifact version
        uses: actions/upload-artifact@v4
        with:
          name: override-placeholder
          path: README.md
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
